# This file is generated by scripts/gen-homebrew-formula.sh in popoffvg/tengo-lsp.
# Do not edit by hand; it is overwritten on every release.
class TengoLsp < Formula
  desc "Language server for the Tengo scripting language"
  homepage "https://github.com/popoffvg/tengo-lsp"
  version "0.2.4"

  on_macos do
    on_arm do
      url "https://github.com/popoffvg/tengo-lsp/releases/download/v#{version}/tengo-lsp-darwin-aarch64.tar.gz"
      sha256 "63c3b097392f2c1fe9453b0dcacdabcd25003231d16bfe7a9bb92a34a98cf036"
    end
    on_intel do
      url "https://github.com/popoffvg/tengo-lsp/releases/download/v#{version}/tengo-lsp-darwin-x86_64.tar.gz"
      sha256 "07e31defbb0e157d6d1c6dc037e231bc3e0dda95cea6c78e3393774cb39fa26c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/popoffvg/tengo-lsp/releases/download/v#{version}/tengo-lsp-linux-aarch64.tar.gz"
      sha256 "c945bb1fbef62e94e5a1f267333eeec7a41f6776802bf3883a94c999ae48f819"
    end
    on_intel do
      url "https://github.com/popoffvg/tengo-lsp/releases/download/v#{version}/tengo-lsp-linux-x86_64.tar.gz"
      sha256 "34cf38e10bf6ecbe25f1c57d2a3a81e44373d94a618ca50c3f7906d43e37f232"
    end
  end

  def install
    bin.install "tengo-lsp"
  end

  test do
    assert_equal "x := 1\n", pipe_output("#{bin}/tengo-lsp fmt", "x := 1\n")
  end
end
