# This file is generated by scripts/gen-homebrew-formula.sh in popoffvg/tengo-lsp.
# Do not edit by hand; it is overwritten on every release.
class TengoLsp < Formula
  desc "Language server for the Tengo scripting language"
  homepage "https://github.com/popoffvg/tengo-lsp"
  version "0.2.5"

  on_macos do
    on_arm do
      url "https://github.com/popoffvg/tengo-lsp/releases/download/v#{version}/tengo-lsp-darwin-aarch64.tar.gz"
      sha256 "b67c11616c2f1b115c789095c9cb135ee1d93b7ebc7c1de3a2b71b635edc7d5f"
    end
    on_intel do
      url "https://github.com/popoffvg/tengo-lsp/releases/download/v#{version}/tengo-lsp-darwin-x86_64.tar.gz"
      sha256 "7d3bd1a34a3eefbb177eaf6beb073aa27d74007be179da86d61a90ae893da515"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/popoffvg/tengo-lsp/releases/download/v#{version}/tengo-lsp-linux-aarch64.tar.gz"
      sha256 "356436888243297e48e0d3751428a174eaffeba8416b44fd69a3cc7ce31abbe9"
    end
    on_intel do
      url "https://github.com/popoffvg/tengo-lsp/releases/download/v#{version}/tengo-lsp-linux-x86_64.tar.gz"
      sha256 "115483b65cb134f5100a10f714a1b1f7ef341b34ef2185142f61beb35471c766"
    end
  end

  def install
    bin.install "tengo-lsp"
  end

  test do
    assert_equal "x := 1\n", pipe_output("#{bin}/tengo-lsp fmt", "x := 1\n")
  end
end
